//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix1._2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int ID { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string mail { get; set; }
        public string telefono { get; set; }
        public string cargo { get; set; }
        public string nombre_Usuario { get; set; }
        public string contrasenia { get; set; }
        public int rol_ID { get; set; }
    }
}
